"""add books table and vector columns

Revision ID: 78e8bf2f5c2b
Revises: 
Create Date: 2026-07-20 18:30:07.265759

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = '78e8bf2f5c2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
        batch_op.add_column(sa.Column('content_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('time_created', sa.DateTime(timezone=True), nullable=False))
        batch_op.create_index(batch_op.f('ix_document_analysis_content_hash'), ['content_hash'], unique=False)

    with op.batch_alter_table('notes_summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note_name', sa.String(length=80), nullable=False))
        batch_op.drop_constraint(batch_op.f('notes_summaries_from_notes_id_key'), type_='unique')

    with op.batch_alter_table('study_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_private', sa.Boolean(), nullable=False,server_default='false'))
        batch_op.add_column(sa.Column('invite_code', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(None, ['invite_code'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('study_groups', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('invite_code')
        batch_op.drop_column('is_private')

    with op.batch_alter_table('notes_summaries', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('notes_summaries_from_notes_id_key'), ['from_notes_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('note_name')

    with op.batch_alter_table('document_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_analysis_content_hash'))
        batch_op.drop_column('time_created')
        batch_op.drop_column('content_hash')
        batch_op.drop_column('embedding')

    # ### end Alembic commands ###
